import { Objective, SpecifiedObjective } from "shared/store/objectives";

/* Foundation Personnel */
export const FPObjectives: SpecifiedObjective<"FP">[] = [
	{
		id: 1,
		priority: 1,
		category: "FP",
		name: "Get worker his coffee",
		description: "Get coffee from a working vending machine and deliver it to the worker",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "CoffeeObjective",
	},
	{
		id: 2,
		priority: 3,
		category: "FP",
		name: "Deliver paperwork",
		description: "Bring a stack of papers from one desk to another",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "PaperworkObjective",
	},
	{
		id: 3,
		priority: 2,
		category: "FP",
		name: "Blackout keywords on research report",
		description: "N/A",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "BlackoutObjective",
	},
	{
		id: 4,
		priority: 1,
		category: "FP",
		name: "Cook and serve food at cafeterias",
		description: "N/A",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "CookAndServeObjective",
	},
];

export const SCDObjectives: SpecifiedObjective<"SCD">[] = [
	{
		id: 5,
		priority: 1,
		category: "SCD",
		name: "Spot amoeba mini game",
		description: "Spot all amoeba in petri dish",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "AmoebaObjective",
	},
	{
		id: 6,
		priority: 1,
		category: "SCD",
		name: "Deliver research reports to office",
		description: "Bring a stack of papers from one desk to another",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "DeliverResearchObjective",
	},
	{
		id: 7,
		priority: 1,
		category: "SCD",
		name: "Conduct research",
		description: "Conduct research by studying papers",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "ConductResearchObjective",
	},
];

export const SDObjectives: SpecifiedObjective<"SD">[] = [
	{
		id: 8,
		priority: 1,
		category: "SD",
		name: "Patrol corridor quest",
		description: "Walk around the facility",
		location: new Vector3(-82.25, 11.1, -22),
		reward: [100, "credits"],
		completion: {
			steps: 0,
		},
		objectiveClass: "PatrolObjective",
	},
	{
		id: 9,
		priority: 1,
		category: "SD",
		name: "Guard CDC quest",
		description: "Stand post for a certain amount of time",
		location: false,
		reward: [100, "credits"],
		completion: {
			timeWatched: 0,
		},
		objectiveClass: "GuardObjective",
	},
	{
		id: 10,
		priority: 1,
		category: "SD",
		name: "File facility reports",
		description: "Escort papers to the other desk",
		location: false,
		reward: [[70, 90], "credits"],
		objectiveClass: "FileObjective",
	},
];

export const EAndTObjectives: SpecifiedObjective<"E&T">[] = [
	{
		id: 11,
		priority: 1,
		category: "E&T",
		name: "Fix wiring",
		description: "Fix electrical wiring in the facility",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "WiringObjective",
	},
	{
		id: 12,
		priority: 1,
		category: "E&T",
		name: "Deliver tool chest",
		description: "Drop off a tool chest at a specified location",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "DeliverToolObjective",
	},
];

export const ClassDObjectives: SpecifiedObjective<"CLASS-D">[] = [
	{
		id: 13,
		priority: 1,
		category: "CLASS-D",
		name: "Sweep floor",
		description: "Pick up broom and sweep the floor",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "MopObjective",
		completion: {
			swept: 0,
		},
	},
	{
		id: 14,
		priority: 1,
		category: "CLASS-D",
		name: "Do X pullups on the bar",
		placeholders: { X: 10 },
		description: "Do pullups on the bar in the gym",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "PullupObjective",
	},
	{
		id: 15,
		priority: 1,
		category: "CLASS-D",
		name: "Make food",
		description: "Cook food in the kitchen",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "CookObjective",
	},
	{
		id: 16,
		priority: 1,
		category: "CLASS-D",
		name: "Kill X security",
		placeholders: { X: 10 },
		description: "Kill security guards in the facility",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "KillSecurityObjective",
	},
	{
		id: 17,
		priority: 1,
		category: "CLASS-D",
		name: "Kill X Mobile Task Forces",
		placeholders: { X: 10 },
		description: "Kill Mobile Task Forces in the facility",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "KillTaskForceObjective",
	},
];

export const MDObjectives: SpecifiedObjective<"MD">[] = [
	{
		id: 18,
		priority: 1,
		category: "MD",
		name: "Conduct Research",
		description: "Conduct research by studying papers",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "MDResearchObjective",
	},
	{
		id: 19,
		priority: 1,
		category: "MD",
		name: "Report Checkup Documents",
		description: "Report checkup documents to the office",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "ReportObjective",
	},
];

export const LogisticsObjectives: SpecifiedObjective<"LOGISTICS">[] = [
	{
		id: 20,
		priority: 1,
		category: "LOGISTICS",
		name: "Deliver crates",
		description: "Deliver crates to a specified location",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "DeliverCratesObjective",
	},
	{
		id: 21,
		priority: 1,
		category: "LOGISTICS",
		name: "Restock supplies",
		description: "Restock supplies in the facility",
		location: false,
		reward: [100, "credits"],
		objectiveClass: "RestockObjective",
	},
];

export const objectives: Objective[] = [
	...FPObjectives,
	...SCDObjectives,
	...SDObjectives,
	...EAndTObjectives,
	...ClassDObjectives,
	...MDObjectives,
	...LogisticsObjectives,
];
