export const images: {
	readonly ui: {
		readonly icons: {
			readonly group: string;
			readonly groupselected: string;
			readonly pencil: string;
			readonly pencilselected: string;
			readonly shirt: string;
			readonly shirtselected: string;
			readonly vest: string;
			readonly customize: string;
			readonly down: string;
			readonly downselected: string;
			readonly downselectedcd: string;
			readonly toparrow: string;
			readonly handgun: string;
			readonly handgunselected: string;
			readonly rifle: string;
			readonly rifleselected: string;
			readonly knife: string;
			readonly knifeselected: string;
			readonly attachments: string;
			readonly attachmentsselected: string;
			readonly arrowright: string;
		};
		readonly glyphs: {
			readonly AD: string;
			readonly CD: string;
			readonly CDselected: string;
			readonly CDhovered: string;
			readonly CI: string;
			readonly DEA: string;
			readonly "E&T": string;
			readonly "E&Tselected": string;
			readonly "E&Thovered": string;
			readonly EC: string;
			readonly FP: string;
			readonly FPselected: string;
			readonly FPhovered: string;
			readonly LD: string;
			readonly LDselected: string;
			readonly LDhovered: string;
			readonly MAND: string;
			readonly MD: string;
			readonly MDselected: string;
			readonly MDhovered: string;
			readonly MTF: string;
			readonly O5C: string;
			readonly SCD: string;
			readonly SCDselected: string;
			readonly SCDhovered: string;
			readonly SD: string;
			readonly SDselected: string;
			readonly SDhovered: string;
		};
		readonly misc: {
			readonly foundationlogo: string;
			readonly divider: string;
			readonly vignette: string;
			readonly objectivemarker: string;
			readonly close: string;
		};
	};
};
