-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		ui = {
			administrativedepartment = "rbxassetid://17097322150",
			classd = "rbxassetid://17097328973",
			dividergradient = "rbxassetid://17095962411",
			downeffect = "rbxassetid://17096718670",
			downeffectfull = "rbxassetid://17096739418",
			engineeringservices = "rbxassetid://17097322223",
			ethicscommittee = "rbxassetid://17097322279",
			foundationlogo = "rbxassetid://17134896666",
			foundationpersonnel = "rbxassetid://17097322340",
			group = "rbxassetid://17095845153",
			headericon = "rbxassetid://17095892780",
			logisticsdepartment = "rbxassetid://17097322391",
			medicaldepartment = "rbxassetid://17097322428",
			mobiletaskforces = "rbxassetid://17097322499",
			pencil = "rbxassetid://17095845207",
			pencil2 = "rbxassetid://17096077643",
			scientificdepartment = "rbxassetid://17097322580",
			securitydepartment = "rbxassetid://17096699811",
			shirt = "rbxassetid://17095845305",
			vest = "rbxassetid://17095845398",
		},
	},
}