-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		ui = {
			glyphs = {
				AD = "rbxassetid://17118730439",
				CD = "rbxassetid://17118730556",
				CI = "rbxassetid://17118730658",
				DEA = "rbxassetid://17118730747",
				["E&T"] = "rbxassetid://17118730855",
				EC = "rbxassetid://17118731057",
				FP = "rbxassetid://17118731201",
				LD = "rbxassetid://17118731351",
				MAND = "rbxassetid://17118731465",
				MD = "rbxassetid://17118731564",
				MTF = "rbxassetid://17118731659",
				O5C = "rbxassetid://17118731742",
				SCD = "rbxassetid://17118731866",
				SD = "rbxassetid://17118732015",
			},
			icons = {
				customize = "rbxassetid://17118732118",
				down = "rbxassetid://17118768967",
				group = "rbxassetid://17118732173",
				pencil = "rbxassetid://17118732290",
				shirt = "rbxassetid://17118732420",
				vest = "rbxassetid://17118732539",
			},
			misc = {
				divider = "rbxassetid://17118757373",
			},
		},
	},
}